apiVersion: v1
kind: Pod
metadata:
  name: __NAME__-pod
  labels:
    uniq: __UNIQUE_ID__
    role: __NAME__
spec:
  containers:
    - name: __NAME__-cntnr
      image: mongo
      command:
        - "numactl"
        - "--interleave=all"
        - "mongos"
        - "--configdb"
        - "__ROUTER_CONFIG__"
        - "--bind_ip_all"
        - "--port"
        - "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: __NAME__-svc
  labels:
    name: __NAME__
    uniq: __UNIQUE_ID__
spec:
  selector:
    role: __NAME__
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
